# Generated by Django 5.2.5 on 2025-09-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
