# Generated by Django 5.2.5 on 2025-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_testimonial",
            field=models.BooleanField(default=False),
        ),
    ]
