# Generated by Django 5.2.5 on 2025-09-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_notification_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="is_testimonial",
        ),
    ]
